### ISSUE TITLE
[API]ボード／タスクにメンバーを割り当てる

### ISSUE THREAD

**Issue by tenkiwizard** [ezaki3/task-board#108]
- ボード
  - 作成・更新時に全ユーザーから選択できる
- タスク
  - 作成・更新時に、ボードに割り当てられたメンバーの中から選択できる

メンバー追加／削除専用のAPIもあった方がいい？

**Comment by ezaki3** [comment]
> メンバー追加／削除専用のAPIもあった方がいい？

今のところは無くても大丈夫そうです！

**Comment by tenkiwizard** [comment]
あ、というか、選択候補一覧自体は、
- ボード作成・更新時
  - `GET /api/v1/users` から取得
- タスク作成・更新時
  - `GET /api/v1/boards/n` から取得

か。その一覧の中からmultipleに選択されたものを、 従来のAPIにPSOT/PATCHする際に、

``` json
{
    "task": {
        "id": 999,
        "members": [
            {"item_id": 999, "user_id": 1},
            {"item_id": 999, "user_id": 3}
        ]
    }
}
```

みたいに付加してもらう感じになりますかね。

**Comment by ezaki3** [comment]
その認識でした！なので専用APIは無くても大丈夫かと。

**Comment by tenkiwizard** [comment]
``` json
{
  "board": {
    "subject": "changed subject",
    "members_attributes": [
      {
        "user_id": 1,
      }
    ]
  }
}
```

こうなりました。 `members_attributes` とするのがRailsの規約のようで。(belongs_toのアソシエーションなら `member_attributes` の模様)

**Comment by tenkiwizard** [comment]
メンバーの削除等についてはUIとの絡みなどあるかと思いますので、別途御見積としましょう!

**Comment by ezaki3** [comment]
Merged #109
