### ISSUE TITLE
README.mdの充実

### ISSUE THREAD

**Issue by tenkiwizard** [ezaki3/task-board#157]

**Comment by tenkiwizard** [comment]
なんとなくこんな方向性でいかがでしょ？

**Comment by ezaki3** [comment]
いいと思います！

**Comment by ezaki3** [comment]
これのフロント側こっちで埋めてプッシュしたらいいですか？

**Comment by tenkiwizard** [comment]
ええ。サーバーサイド他もまだ行数増やすつもりですのでお互い書き足して都度プッシュしていって、第5フェーズの終わりの方ででもいったんマージできれば、のような計画です!

**Comment by ezaki3** [comment]
書き足してみました。
