### ISSUE TITLE
付箋のところにアバター表示したい

### ISSUE THREAD

**Issue by ezaki3** [ezaki3/task-board#158]

**Comment by tenkiwizard** [comment]
いったんマージしてみましたが、ボード一覧のドロップダウン時のアバターが巨大化している？

**Comment by ezaki3** [comment]
おっと、css変更したんですけど対応が漏れてたようですね。修正します。

**Comment by tenkiwizard** [comment]
バッチグー夫です!
デザインについては迂闊に右寄せなどすると、アバターが複数行になったときなどまた制御が心許なくなりそうな気もしますので、今のところはシンプルでよろしいのではないかと思います!!
