### ISSUE TITLE
main.htmlをRailsアプリに組み込む

### ISSUE THREAD

**Issue by tenkiwizard** [ezaki3/task-board#25]
URIは `/boards`
- ルーティング設定
- コントローラ作成
- layout / view切り出し
- assets類どうするか。。

**Comment by tenkiwizard** [comment]
rails風に組み込み・切り出しやってみたのですが、assetsの扱いがよくわかってないです。
そのせいか、タスクを追加した後の挙動が変になってしまいました。何か足りていないのかな？？
あとこの辺、Grunt側でやってる処理と整合性合わせる必要あり？少なくともGruntfileは修正しなきゃですね。

そんなわけでもろもろちょっとご確認・修正のほどお願いします。

**Comment by ezaki3** [comment]
了解です！ありがとうございます

**Comment by ezaki3** [comment]
タスクを追加した後の挙動について、head内とページ下部で同じjsをincludeしてたのが影響してたみたいです。同様にbootstrap.min.cssも重複してたので片方を削除しました。

javascriptはhead内ではなく、ページ下部に書くのが今風みたいですね。  
htmlをほぼほぼ読み込んでからjavascriptを読み込んだ方がwebページの表示速度が早くなるとか。

あとは画面上の「Add a task...」のリンク部分がrails側で持ってるscaffolds.cssのスタイルが適用されていて若干気になりますが、追々削除すればいいと思います。

**Comment by tenkiwizard** [comment]
あとはこちらも追々ですが、rails側のturbolinksとかasset piplineなんかの仕組みとjs側の作法をどのように融合させていくのが正しいのか、といったあたりの研究が必要となりそうですねー
