### ISSUE TITLE
メイン画面HTMLモック作成

### ISSUE THREAD

**Issue by ezaki3** [ezaki3/task-board#6]
メインとなるカンバン画面
- グループ分けされたタスクの一覧
- タスクの追加/編集(モーダル)
- グループの追加/編集(モーダル)

**Comment by tenkiwizard** [comment]
ここでいう「グループ」てのは、Trelloでいうところの「list」に相当するものですかね？

**Comment by ezaki3** [comment]
そうです！更に言うとラベルとして
- ボード名

も盛り込む予定です。アカウントの概念を持たないかもしれないので、Trelloでいうところのボードを切り替えたりだとか、アカウント関連のメニューは当初無しの方向で。

**Comment by tenkiwizard** [comment]
なるほどりょうかいです!
