### ISSUE TITLE
ドラッグ&ドロップ時の並び順変更に対応するAPI

### ISSUE THREAD

**Issue by tenkiwizard** [ezaki3/task-board#73]
- 並び順に関するAPI側処理の実装
  - 新規作成時の初期値設定
  - ~~削除時の並び順振り直し（必要であれば）~~
    - 内部的には歯脱けデータのままとする方向で…
  - 並び順変更、グループ付け替え時の並び順振り直し

**Comment by ezaki3** [comment]
確認なんですがここまでで実装されてるのって、
- 新規作成時の初期値設定

と、それに付随して一覧取得時の並び順に反映されるようにしたって感じでよかったですか？
- 並び順変更、グループ付け替え時の並び順振り直し

に関しては別途な感じですかね。

**Comment by tenkiwizard** [comment]
ありゃ、そこそこは動くかと期待していたのですがダメぽですかね？

**Comment by ezaki3** [comment]
例えば
- グループ1
  - タスク1
  - タスク2

ってのがあって、それをドラッグアンドドロップで
- グループ1
  - タスク2
  - タスク1

にした時なんですけど、フロントからそれぞれ
PATCH /api/v1/tasks/タスク2→priority=1
PATCH /api/v1/tasks/タスク1→priority=2
を叩く流れですか？

ここのところが↑の実装だとタスク数が増えればその分APIのアクセス数が増えてしまうので、そこそこ動いてくれる別の何かがあればと期待しておりました。

**Comment by tenkiwizard** [comment]
なるほど。

`PATCH /api/v1/tasks/タスク2→priority=1`

だけで表向きはそれっぽく動くようにしたつもりだったのですが、テストを書いていて気付いたバグがあって、推定挙動不審なのですよねー。
priorityが3種類以上存在するケースじゃないとドラッグできない状態かなー。
仕様としては、
- ドラッグしたオブジェクトだけPATCHリクエスト1回叩けばOK
- その際、当該オブジェクトの新priority**以下**のpriorityを持つオブジェクトのpriority値が一律インクリメントされる

としたいですｗ

**Comment by ezaki3** [comment]
なるほど！ナイスな仕様ですねw 了解しましたー！
ではフロント側もその方向で進めます

**Comment by ezaki3** [comment]
フロント側でゴニョゴニョして気がついた点を報告をば。
- 並べ替えをせずに編集した場合でもpriority値がインクリメントされてしまう

また、歯抜けデータがあった場合、
- priority1のタスク
- priority3のタスク

priority1のタスクをドラッグアンドドロップでpriority3のタスクの下に移動した時、priority1のタスクはpriority2になるも、priority3よりは上位となるので並び変わらない（リロードすると元に戻る）という現象も確認しました。

**Comment by tenkiwizard** [comment]
ご報告あざます!ここマジ難しいっすｗ
テストケース書くたびにどこかバグってますですはい。
しばしお待ちをば。

**Comment by ezaki3** [comment]
Merged #76 #77
