### ISSUE TITLE
[API]タスクドラッグ&ドロップ時の並べ替え不備？

### ISSUE THREAD

**Issue by tenkiwizard** [ezaki3/task-board#79]
動かしてみて気になったのは、
- タスク1
- タスク2

を
- タスク2
- タスク1

とするのに、タスク2をドラッグするのは問題ないのですが、タスク1をドラッグすると、タスク1のpriorityは2になるも、タスク2のpriorityが3になってしまい並び変わらないという現象が出ています。

**Comment by tenkiwizard** [comment]
@ezaki3 あーなんとなく。見たところ、
- フロント
  - 絶対位置？的な値でリクエストすることを想定
- API
  - 直近上下？のいずれかまたは両方のタスクから算出した相対値でのリクエストを期待

みたいなところで挙動に齟齬がでている感じすかねー(用語テキトー御容赦)
いよいよ仕様決めねばならぬときが来ましたかねｗ

**Comment by ezaki3** [comment]
なんとなく送信するパラメータの問題かとも思ってました。
ruby力が足りずコードを追いきれて無かったのでノリで実装しましたが上手く行かなかったですw

相対値ということは、
- タスク1(priority: 1)
- タスク2(priority: 2)

タスク1をタスク2の下にドラッグアンドドロップした場合は
- タスク2(priority: 2)
- タスク1(priority: 3)

でおｋですか？であればその路線で調整しますー

**Comment by tenkiwizard** [comment]
ですです!そう作りたかったつもりです!!できているのかどうかはよくわかりません!!!
しかしその仕様が[美しい | 妥当]なのかどうかも甚だ疑問と今回あいなりましたなわけでして。
別板でご提案いただきました通り、オフ会で決めましょう!

**Comment by tenkiwizard** [comment]
API側の仕様を変更するようオフ会にて方針決定

**Comment by tenkiwizard** [comment]
挙動はなんとなくそれっぽくなったくさい。
それに伴い、モデル群をリファクタリングしたので、テストもそれに合わせてDRYにリファクタリングせねばーが残タスク。
- http://ria10.hatenablog.com/entry/20140103/1388757935
- http://qiita.com/mmyoji/items/110b39e950d0f0dce75a

らへんを取っかかりに試してみる予定でがす。
