### ISSUE TITLE
タスク削除、移動時のpriority値

### ISSUE THREAD

**Issue by ezaki3** [ezaki3/task-board#82]
- タスク1(priority: 1)
- タスク2(priority: 2)
- タスク3(priority: 3)

タスク2を削除、または他グループへ移動させた時に
- タスク1(priority: 1)
- タスク3(priority: 3)

となり、タスク1をタスク3の下にドラッグアンドドロップした時
- タスク1(priority: 2)
- タスク3(priority: 3)

となって並び変わらないです。

**Comment by tenkiwizard** [comment]
ついでに、親リソースを削除した際にはその子リソース群もいもづるで削除するようにする。

**Comment by ezaki3** [comment]
Merged #83
